unity_bin : /Applications/Unity/Hub/Editor/2019.4.26f1c1/Unity.app/Contents/MacOS/Unity  #unity可执行文件
unity_proj : /Users/mac/data0/public_work/pinyin-unity-android/proj/pinyin               #unity工程路径
log_output_path : /Users/mac/data0/public_work/pinyin-unity-android/build                #unity日志输路径

#-----------------------android配置-----------------------                                  
android:
  - na_path : /Users/mac/data0/public_work/pinyin_android
  - method : ZybEditor.PerformBuildAndroid.ExportProjAsset

#-----------------------android配置-----------------------                                  


#-----------------------iOS配置-----------------------                                  
ios :
  - na_path : /Users/mac/data0/public_work/pinyin_ios
  - method : ZybEditor.PerformBuild.ExportProjAsset
#-----------------------iOS配置-----------------------

args: -quit -batchmode      #通用参数






